### PR TITLE
Major Update in CSV Parser & DataGenerator

### PR DESCRIPTION
**Pull request by nikhilbhatia22**
Changes:

dataGenerator will now generate values in the same pattern as of Pankaj
Bhai's CSV file...

and thus parsers are updated for such format....

Also, some optimization and automation is made in parsers

==================================
Please test it once before merging it... i can't test parser through
RAM's public folder...

### CODE REVIEW

**Comment by pratik** [comment]
tested right?

**Comment by nikhilbhatia22** [comment]
I have tested for my personal repo of parser... I can't test parser through
/public/parser...  You need to test it once... It will work for sure...
But just for the sake of confirmation....  Test it...

**Comment by pratik** [comment]
Why can't you test parser through /public/parser

**Comment by nikhilbhatia22** [comment]
Wamp hangs up...  Dnt knw why...

**Comment by pratik** [comment]
can't merge then. How many requests per minute?

**Comment by nikhilbhatia22** [comment]
:|

Parser hai be...  Totally server based...  Isme kaha request?.. Continuous
chalne wala...  Aur phir auto refresh wala...

Wamp ki prob abhi nahi aayi hai means after i made changes...  Ye starting
se hai...  Jan - Feb me last test kiya tha through public/parser... And
something was gng wrong...

Chaiye to TV pe aa kar dekh le!

**Comment by pratik** [comment]
Cool man!

**Pull request merged**
